version: '3.8'

services:

## no gui docker image
  # no_gui:
  #   build: 
  #     dockerfile: Dockerfile2
  #     context: .
  #     network: host    
  #   volumes:
  #       - $HOME/datasets/:/datasets/
  #   network_mode: "host" 

## gui docker image
  gui:
    build: 
      dockerfile: Dockerfile
      context: .
      network: host    
    volumes:
        - $HOME/datasets/:/datasets/
        - /dev/shm:/dev/shm
    environment:
      - RESOLUTION=1920x1080
    ports:
      - 6080:80
      - 5002:5002

## gpu allocation
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2            
              capabilities: [gpu]
