version: '3.8'

services:
  api:
    build: 
      context: .
      network: host    
    volumes:
        - /home/uwcviss/projects/NeRF-SLAM/datasets/:/project/NeRF-SLAM/datasets/
    network_mode: "host" 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2            
              capabilities: [gpu]