parallel_run: True
multi_gpu: True
initial_k: 0
final_k: -1
img_stride: 2
stereo: False
weights: droid.pth
buffer: 100
dataset_name: nerf
mask_type: ours
gui: True
slam: True
fusion: nerf 
width: 0
height: 0
network: ""
eval: False
create_view_per_iters: 100